<h2 class="text-xl font-bold leading-6 text-gray-900">Transaction History</h2>
    <p class="mt-1 text-sm text-gray-500">A log of all membership-related payments.</p><div class="mt-4 bg-white rounded-lg shadow-sm border border-slate-200"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200"><thead class="bg-gray-50"><tr><th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Date</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Amount</th><th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Method</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Proof</th><th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Receipt#</th>
                        <th class="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase">Actions</th></tr>
                </thead><tbody class="bg-white divide-y divide-gray-200"><tr><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-600">Oct 15,
2025,
1: 44 AM</td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">K10.00</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 capitalize">cash</td>
                                
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    <br /><font size='1'><table class='xdebug-error xe-uncaught-exception'dir='ltr'border='1'cellspacing='0'cellpadding='1'><tr><th align='left'bgcolor='#f57900'colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>(!)</span> Fatal error: Uncaught TypeError: basename(): Argument #1 ($path) must be of type string, array given in C:\wamp64\www\membersyncweb\api\users\get_view_data.php on line <i>230</i></th></tr><tr><th align='left'bgcolor='#f57900'colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>(!)</span> TypeError: basename(): Argument #1 ($path) must be of type string, array given in C:\wamp64\www\membersyncweb\api\users\get_view_data.php on line <i>230</i></th></tr><tr><th align='left'bgcolor='#e9b96e'colspan='5'>Call Stack</th></tr><tr><th align='center'bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left'bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left'bgcolor='#eeeeec'>Location</th></tr><tr><td bgcolor='#eeeeec'align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0002</td><td bgcolor='#eeeeec'align='right'>447696</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64\www\membersyncweb\public\index.php'bgcolor='#eeeeec'>...\index.php<b>: </b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec'align='center'>0.0054</td><td bgcolor='#eeeeec' align='right'>468464</td><td bgcolor='#eeeeec'>require_once(<font color='#00bb00'>'C:\wamp64\www\membersyncweb\api\users\get_view_data.php</font> )</td><td title='C: \wamp64\www\membersyncweb\public\index.php ' bgcolor='#eeeeec '>...\index.php<b>:</b>21</td></tr>
<tr><td bgcolor='#eeeeec ' align='center '>3</td><td bgcolor='#eeeeec ' align='center '>0.0639</td><td bgcolor='#eeeeec ' align='right '>681288</td><td bgcolor='#eeeeec '><a href='http: //www.php.net/function.basename' target='_new'>basename</a>( <span>$path = </span><span>[&#39;size&#39; =&gt; 2363, &#39;filename&#39; =&gt; &#39;68eee04955268-pdfndoc.pdf&#39;, &#39;original_name&#39; =&gt; &#39;pdfndoc.pdf&#39;]</span> )</td><td title='C:\wamp64\www\membersyncweb\api\users\get_view_data.php' bgcolor='#eeeeec'>...\get_view_data.php<b>:</b>230</td></tr>
</table></font>
