<?php
// /api/members/purchase.php
header('Content-Type: application/json');

require_once dirname(__DIR__) . '/core/initialize.php'; // Adjusted path
require_once dirname(__DIR__) . '/core/mailer.php';     // Adjusted path
require_once dirname(__DIR__) . '/core/PdfGenerator.php'; // Adjusted path

$data = $_POST;
$db = (new Database())->connect();
$db->beginTransaction();

try {
    // --- 1. VALIDATION ---
    $user_id = filter_var($data['user_id'] ?? null, FILTER_VALIDATE_INT);
    $action = $data['action'] ?? 'create';
    $subscription_id = filter_var($data['subscription_id'] ?? null, FILTER_VALIDATE_INT);
    $membership_type_id = filter_var($data['membership_type_id'] ?? null, FILTER_VALIDATE_INT);
    $amount_paid = isset($data['amount_paid']) && is_numeric($data['amount_paid']) ? (float)$data['amount_paid'] : 0.0;
    $payment_method = $data['payment_method'] ?? null;
    $generated_order_id = $data['generated_order_id'] ?? null; // Get the ID generated by frontend for Malipo

    // Basic Validations
    if (!$user_id) throw new Exception("User ID is required.");
    if (($action === 'create' || $action === 'update') && !$membership_type_id) throw new Exception("Membership Type required.");
    if ($action === 'add_payment' && !$subscription_id) throw new Exception("Subscription ID required for payment.");
    if ($amount_paid > 0 && !$payment_method) throw new Exception("Payment method required when paying.");
    if ($amount_paid < 0) throw new Exception("Amount paid cannot be negative.");

    $allowed_methods = ['cash', 'card', 'mobile_money', 'bank_transfer', 'gateway'];
    if ($payment_method && !in_array($payment_method, $allowed_methods)) {
        throw new Exception("Invalid payment method.");
    }
    // Gateway requires the generated order ID to be present now
    if ($payment_method === 'gateway' && empty($generated_order_id)) {
         throw new Exception("Generated Order ID is required for gateway payments.");
    }

    // --- 2. GET USER & MEMBERSHIP TYPE DETAILS ---
    $stmt_user = $db->prepare("SELECT full_name, email FROM users WHERE id = ?");
    $stmt_user->execute([$user_id]);
    $user = $stmt_user->fetch(PDO::FETCH_ASSOC);
    if (!$user) throw new Exception("User not found.");

    $type = null;
    if ($membership_type_id) {
        $stmt_type = $db->prepare("SELECT fee, renewal_month, name as type_name FROM membership_types WHERE id = ?");
        $stmt_type->execute([$membership_type_id]);
        $type = $stmt_type->fetch(PDO::FETCH_ASSOC);
        if (!$type) throw new Exception("Invalid membership type.");
    }

    // --- 3. INITIALIZE ---
    $pdfGenerator = new PdfGenerator();
    $attachments = [];
    $reference_id = null;
    $email_subject = "Your Membership Documents";
    $email_body = "Dear " . htmlspecialchars($user['full_name']) . ",\n\nPlease find attached documents related to your membership.";
    $type_name_for_receipt = 'Membership Payment';
    $is_gateway_payment = ($payment_method === 'gateway');


    // =================================================================
    // --- 4. ACTION-SPECIFIC LOGIC ---
    // =================================================================

    if ($action === 'add_payment') {
        // For adding payment, we assume subscription already exists.
        $reference_id = $subscription_id;
        if ($amount_paid <= 0 && !$is_gateway_payment) {
             throw new Exception("Payment amount must be > 0 for manual payment.");
        }

        $stmt_sub = $db->prepare("SELECT ms.balance_due, ms.invoice_id, mt.name as type_name
                                 FROM membership_subscriptions ms
                                 JOIN membership_types mt ON ms.membership_type_id = mt.id
                                 WHERE ms.id = ? AND ms.user_id = ?");
        $stmt_sub->execute([$subscription_id, $user_id]);
        $subscription = $stmt_sub->fetch(PDO::FETCH_ASSOC);
        if (!$subscription) throw new Exception("Subscription not found.");

        $type_name_for_receipt = $subscription['type_name'] ?? $type_name_for_receipt;

        // --- For Non-Gateway: Update Subscription/Invoice Immediately ---
        if (!$is_gateway_payment) {
            $current_balance = (float)$subscription['balance_due'];
            $new_balance_due = max(0, $current_balance - $amount_paid);
            $paid_this_transaction = $current_balance - $new_balance_due;

            if ($paid_this_transaction > 0) {
                $new_status = ($new_balance_due <= 0) ? 'active' : 'pending';
                $db->prepare("UPDATE membership_subscriptions SET balance_due = ?, status = ? WHERE id = ?")
                   ->execute([$new_balance_due, $new_status, $subscription_id]);

                if ($subscription['invoice_id']) {
                    $inv_status = ($new_balance_due <= 0) ? 'paid' : 'partially_paid';
                    $inv_fetch_stmt = $db->prepare("SELECT total_amount FROM invoices WHERE id = ?");
                    $inv_fetch_stmt->execute([$subscription['invoice_id']]);
                    $inv_total = $inv_fetch_stmt->fetchColumn();
                    $new_paid_amount_inv = $inv_total ? max(0, (float)$inv_total - $new_balance_due) : $amount_paid;

                    $db->prepare("UPDATE invoices SET paid_amount = ?, balance_due = ?, status = ? WHERE id = ?")
                       ->execute([$new_paid_amount_inv, $new_balance_due, $inv_status, $subscription['invoice_id']]);

                    // Generate updated invoice PDF if requested
                    if (isset($data['issue_invoice']) && $data['issue_invoice'] == 'on') {
                         // (Invoice generation logic as before)
                         $inv_stmt = $db->prepare("SELECT * FROM invoices WHERE id = ?");
                         $inv_stmt->execute([$subscription['invoice_id']]);
                         $invoice = $inv_stmt->fetch(PDO::FETCH_ASSOC);
                         if ($invoice) {
                             $invoice_data = [ /* ... invoice data ... */];
                             $attachments[] = ['content' => $pdfGenerator->generateMembershipInvoicePdf($invoice_data), 'filename' => 'Invoice-' . $invoice['id'] . '.pdf'];
                             $email_subject = "Membership Payment Received & Updated Invoice";
                             $email_body = "Dear " . htmlspecialchars($user['full_name']) . ",\n\nPayment received. Updated documents attached.";
                         }
                    }
                }
            }
        }
        // For gateway, subscription/invoice are updated by callback

    } else { // --- LOGIC FOR CREATE AND UPDATE ---
        if (!$type) throw new Exception("Membership type details missing.");

        $membership_fee = (float)$type['fee'];
        // For gateway, balance is the full fee initially, payment reduces it via callback
        // For manual, balance is fee minus amount paid now
        $initial_balance_due = $is_gateway_payment ? $membership_fee : max(0, $membership_fee - $amount_paid);
        $initial_status = ($is_gateway_payment && $membership_fee > 0) ? 'pending' : (($initial_balance_due <= 0) ? 'active' : 'pending'); // Gateway starts pending unless free

        $start_date_str = $data['start_date'] ?? date('Y-m-d');
        try { $start_date = new DateTime($start_date_str); } catch (Exception $e) { throw new Exception("Invalid start date."); }
        $renewal_months = isset($type['renewal_month']) && $type['renewal_month'] > 0 ? (int)$type['renewal_month'] : 12;
        $end_date = (clone $start_date)->modify('+' . $renewal_months . ' months');

        if ($action === 'update' && $subscription_id) {
            $expire_date = (clone $start_date)->modify('-1 day');
            $db->prepare("UPDATE membership_subscriptions SET status = 'expired', end_date = ? WHERE id = ? AND user_id = ? AND status != 'expired'")
               ->execute([$expire_date->format('Y-m-d'), $subscription_id, $user_id]);
            $email_subject = "Your Membership Update Documents";
            $email_body = "Dear " . htmlspecialchars($user['full_name']) . ",\n\nMembership updated. Documents attached.";
        }

        $card_number = 'MS-' . $user_id . '-' . time();
        $sub_query = "INSERT INTO membership_subscriptions (user_id, membership_type_id, start_date, end_date, membership_card_number, status, balance_due) VALUES (?, ?, ?, ?, ?, ?, ?)";
        $stmt_sub = $db->prepare($sub_query);
        if (!$stmt_sub->execute([$user_id, $membership_type_id, $start_date->format('Y-m-d'), $end_date->format('Y-m-d'), $card_number, $initial_status, $initial_balance_due])) {
             throw new Exception("Failed to create subscription record.");
        }
        $new_subscription_id = $db->lastInsertId();
        if(!$new_subscription_id) throw new Exception("Failed to get new subscription ID.");
        $reference_id = $new_subscription_id;

        // Issue Invoice if requested (Status depends on if gateway or manual)
        if (isset($data['issue_invoice']) && $data['issue_invoice'] == 'on') {
            $due_date = (new DateTime())->modify('+30 days');
            $inv_query = "INSERT INTO invoices (user_id, related_type, related_id, total_amount, paid_amount, balance_due, status, due_date) VALUES (?, 'membership', ?, ?, ?, ?, ?, ?)";
            // For gateway, paid amount is 0 initially, balance is full fee, status unpaid
            // For manual, use the actual amounts paid/due now
            $inv_paid = $is_gateway_payment ? 0.00 : $amount_paid;
            $inv_balance = $is_gateway_payment ? $membership_fee : $initial_balance_due;
            $inv_status = $is_gateway_payment ? 'unpaid' : ($inv_balance <= 0 ? 'paid' : ($inv_paid > 0 ? 'partially_paid' : 'unpaid'));

            if (!$db->prepare($inv_query)->execute([$user_id, $new_subscription_id, $membership_fee, $inv_paid, $inv_balance, $inv_status, $due_date->format('Y-m-d')])) {
                 throw new Exception("Failed to create invoice record.");
            }
            $invoice_id = $db->lastInsertId();
             if(!$invoice_id) throw new Exception("Failed to get new invoice ID.");

            $db->prepare("UPDATE membership_subscriptions SET invoice_id = ? WHERE id = ?")->execute([$invoice_id, $new_subscription_id]);

            // Generate and attach invoice PDF
            $invoice_data = [ /* ... invoice data using $inv_paid, $inv_balance ... */
                'invoice_id' => $invoice_id, 'user_name' => $user['full_name'], 'membership_type' => $type['type_name'],
                'issued_at' => date('Y-m-d H:i:s'), 'due_date' => $due_date->format('Y-m-d'),
                'total_amount' => $membership_fee, 'paid_amount' => $inv_paid, 'balance_due' => $inv_balance
            ];
            $attachments[] = ['content' => $pdfGenerator->generateMembershipInvoicePdf($invoice_data), 'filename' => 'Invoice-' . $invoice_id . '.pdf'];
            $email_subject = "Your New Membership Invoice";
            $email_body = "Dear " . htmlspecialchars($user['full_name']) . ",\n\nMembership created. Invoice attached.";
        }
         $type_name_for_receipt = $type['type_name'];
    }

    // =================================================================
    // --- 5. SHARED LOGIC: PAYMENT RECORD & (Manual) RECEIPT ---
    // =================================================================
    if ($amount_paid > 0 || $is_gateway_payment) { // Record payment even if amount is 0 for gateway initiation? Yes, to store order_id.
        if (!$reference_id) throw new Exception("Cannot record payment without reference ID.");

        $proof_path = null;
        // Set payment status: 'pending' for gateway, 'completed' for manual
        $payment_status = $is_gateway_payment ? 'pending' : 'completed';
        // Use generated_order_id for gateway, null otherwise, in the field previously holding Malipo's ID
        $gateway_id_to_store = $is_gateway_payment ? $generated_order_id : null;

        // Handle proof upload ONLY for non-gateway methods
        if (!$is_gateway_payment && isset($_FILES['payment_proof']) && $_FILES['payment_proof']['error'] === UPLOAD_ERR_OK) {
              // (Proof upload logic as before...)
              $upload_dir = dirname(__DIR__, 3) . '/uploads/proofs/';
              if (!is_dir($upload_dir)) @mkdir($upload_dir, 0755, true); // Suppress errors if exists
              $original_filename = basename($_FILES['payment_proof']['name']);
              $safe_filename = preg_replace("/[^a-zA-Z0-9.\-_]/", "_", $original_filename);
              $filename = 'proof_' . $reference_id . '_' . uniqid() . '_' . $safe_filename;
              if(move_uploaded_file($_FILES['payment_proof']['tmp_name'], $upload_dir . $filename)) {
                  $proof_path = '/uploads/proofs/' . $filename;
              } else {
                  error_log("Failed to move uploaded file: " . $original_filename);
              }
        }

        $meta_data = [];
        if ($proof_path) $meta_data['proof_of_payment'] = $proof_path;
        $meta_json = !empty($meta_data) ? json_encode($meta_data) : null;

        $pay_query = "INSERT INTO payments (user_id, payment_type, reference_id, amount, method, status, gateway_transaction_id, meta) VALUES (?, 'membership', ?, ?, ?, ?, ?, ?)";
        $stmt_pay = $db->prepare($pay_query);
        // Store our generated order_id in gateway_transaction_id for pending gateway payments
        if (!$stmt_pay->execute([$user_id, $reference_id, $amount_paid, $payment_method, $payment_status, $gateway_id_to_store, $meta_json])) {
              throw new Exception("Failed to record payment. Error: " . implode(" | ", $stmt_pay->errorInfo()));
        }
        $payment_id = $db->lastInsertId();
        if(!$payment_id) throw new Exception("Failed to get new payment ID.");

        // Issue Receipt only if requested AND it's NOT a gateway payment (receipt for gateway is done in callback)
        if (!$is_gateway_payment && isset($data['issue_receipt']) && $data['issue_receipt'] == 'on' && $amount_paid > 0) {
            $receipt_num = 'RCPT-MEM-' . date('Ymd') . '-' . $payment_id;
             if (!$db->prepare("INSERT INTO receipts (payment_id, receipt_number) VALUES (?, ?)")->execute([$payment_id, $receipt_num])) {
                  error_log("Failed to create receipt record for payment $payment_id.");
             } else {
                 $receipt_data = [ /* ... receipt data ... */
                     'receipt_num' => $receipt_num,
                     'user_name' => $user['full_name'],
                     'amount_paid' => $amount_paid,
                     'membership_type' => $type_name_for_receipt,
                     'payment_method' => $payment_method,
                     'transaction_date' => date('Y-m-d H:i:s'),
                     'gateway_ref' => null // No gateway ref for manual
                 ];
                  $attachments[] = ['content' => $pdfGenerator->generateMembershipReceiptPdf($receipt_data), 'filename' => $receipt_num . '.pdf'];
                  // Adjust email subject/body if only receipt is sent
                  if (!(isset($data['issue_invoice']) && $data['issue_invoice'] == 'on')) {
                      $email_subject = "Your Membership Payment Receipt";
                      $email_body = "Dear " . htmlspecialchars($user['full_name']) . ",\n\nPayment received. Receipt attached.";
                  }
            }
        }
    }

    // =================================================================
    // --- 6. SEND EMAILS (Only Invoices for Gateway) & FINALIZE ---
    // =================================================================
    // Send email ONLY IF attachments exist (Invoice for gateway, Invoice+Receipt for manual)
    if (!empty($attachments)) {
        try {
            $mailer = new Mailer();
            $email_body_formatted = nl2br(htmlspecialchars($email_body));
            $mailer->send($user['email'], $user['full_name'], $email_subject, $email_body_formatted, $attachments);
        } catch (Exception $mailError) {
             error_log("Mailer Error in purchase.php (UserID $user_id): " . $mailError->getMessage());
        }
    }

    $db->commit();
    // Modify success message for gateway
    $success_message = $is_gateway_payment ? 'Membership record created. Please proceed with MALIPO payment.' : 'Membership processed successfully.';
    echo json_encode(['success' => true, 'message' => $success_message]);

} catch (PDOException $e) {
    if ($db && $db->inTransaction()) $db->rollBack();
    http_response_code(500);
    error_log("DB Error purchase.php: " . $e->getMessage());
    echo json_encode(['success' => false, 'message' => 'Database error. Ref: PDB']);

} catch (Exception $e) {
    if ($db && $db->inTransaction()) $db->rollBack();
    http_response_code(400);
    error_log("App Error purchase.php: " . $e->getMessage());
    echo json_encode(['success' => false, 'message' => $e->getMessage()]);
}
?>